version: "0.1"
services:
  broker:
    build: man-scouts/broker
    ports:
      - "8080:8080"
    depends_on:
      - "eureka-server"
  mysql-server:
    image: mysql/mysql-server:latest
    ports:
      - "3307:3306"
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
  euro-scout:
    build: man-scouts/euro-scout
    ports:
      - "8081:8081"
    depends_on:
      - "mysql-server"
  africa-scout:
    build: man-scouts/africa-scout
    ports:
      - "8082:8082"
    depends_on:
      - "mysql-server"
  americas-scout:
    build: man-scouts/americas-scout
    ports:
      - "8083:8083"
    depends_on:
      - "mysql-server"
  asia-oceania-scout:
    build: man-scouts/asia_oceania-scout
    ports:
      - "8084:8084"
    depends_on:
      - "mysql-server"
  field-scout:
    build: man-scouts/field-scout
    ports:
      - "8085:8085"
    depends_on:
      - "mysql-server"
    profiles:
      - demo
  api:
    build: client/
    ports:
      - "8000:8000"
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
  web:
    build: client/myapp_v2
    ports:
      - "3000:3000"
  redis:
    image: redis
    ports:
      - "6379:6379"
  eureka-server:
    build: man-scouts/eureka-server
    ports:
      - "8761:8761"

